### ISSUE TITLE
Is it possible to introduce preview channels?

### ISSUE THREAD

**Issue by simpros** [simonnepomuk/monorepo#1]
Hi, I was wondering if there is the possibility to include preview channels somehow 🤔

Great work so far!

**Comment by simonnepomuk** [comment]
I think preview channels should work out of the box. Have you tried using the commands linked in the [docs](https://firebase.google.com/docs/hosting/manage-hosting-resources#cli-commands-preview-channels-cloning)?

**Comment by CodeCakePie** [comment]
I think for the static hosting yes, but what about the ssr function 🤔

Tbh, I am not very deep into firebase, but for my understanding these commands would only target the hosting part, but not the ssr function

**Comment by simonnepomuk** [comment]
Ah yes, just had a brief look and overlooked the hosting part. Looks like Firebase [doesn't support preview channels for functions yet](https://stackoverflow.com/questions/68582776/how-to-use-firebase-hosting-preview-channel-to-test-cloud-functions). I'm not sure if implementing workarounds should be in the scope of the adapter. I think if you want to work with previews for functions you would need to go the route described in the linked stackoverflow post.

**Comment by simonnepomuk** [comment]
I'm trying to integrate the web framework support which firebase recently launched in beta, which should allow for preview channels. I'm currently a bit stuck and opened an issue at firebase [here](https://github.com/FirebaseExtended/firebase-framework-tools/issues/53)
